apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-workshop.fullname" . }}
  labels:
    {{- include "kafka-workshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-workshop.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" ((include "kafka-workshop.fullname" .) | trunc 54 | trimSuffix "-") }}
  labels:
    {{- include "kafka-workshop.labels" . | nindent 4 }}
    collect-metrics: "true"
spec:
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: http-metrics
      name: http-metrics
  selector:
    {{- include "kafka-workshop.selectorLabels" . | nindent 4 }}
