apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: petshop
  namespace: petshop
spec:
  kafka:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-rule.runner
                      operator: In
                      values:
                        - kafka
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"

    version: 3.2.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 32100
          brokers:
            - broker: 0
              nodePort: 32101
              advertisedHost: broker-0.cluster.dissi.me
              advertisedPort: 32101

    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      type: ephemeral
  zookeeper:
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    userOperator:
      watchedNamespace: petshop
      reconciliationIntervalSeconds: 60
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
