/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dissi.kafkaworkshop.kubernetes.kafka.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * Quotas on requests to control the broker resources used by clients. Network bandwidth and request rate quotas can be
 * enforced.Kafka documentation for Kafka User quotas can be found at
 * http://kafka.apache.org/documentation/#design_quotas.
 */
@ApiModel(description = "Quotas on requests to control the broker resources used by clients. Network bandwidth and request rate quotas can be enforced.Kafka documentation for Kafka User quotas can be found at http://kafka.apache.org/documentation/#design_quotas.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-23T10:08:26.048Z[Etc/UTC]")
public class V1alpha1KafkaUserSpecQuotas {

  public static final String SERIALIZED_NAME_CONSUMER_BYTE_RATE = "consumerByteRate";
  @SerializedName(SERIALIZED_NAME_CONSUMER_BYTE_RATE)
  private Integer consumerByteRate;

  public static final String SERIALIZED_NAME_CONTROLLER_MUTATION_RATE = "controllerMutationRate";
  @SerializedName(SERIALIZED_NAME_CONTROLLER_MUTATION_RATE)
  private BigDecimal controllerMutationRate;

  public static final String SERIALIZED_NAME_PRODUCER_BYTE_RATE = "producerByteRate";
  @SerializedName(SERIALIZED_NAME_PRODUCER_BYTE_RATE)
  private Integer producerByteRate;

  public static final String SERIALIZED_NAME_REQUEST_PERCENTAGE = "requestPercentage";
  @SerializedName(SERIALIZED_NAME_REQUEST_PERCENTAGE)
  private Integer requestPercentage;


  public V1alpha1KafkaUserSpecQuotas consumerByteRate(Integer consumerByteRate) {

    this.consumerByteRate = consumerByteRate;
    return this;
  }

  /**
   * A quota on the maximum bytes per-second that each client group can fetch from a broker before the clients in the
   * group are throttled. Defined on a per-broker basis.
   * minimum: 0
   *
   * @return consumerByteRate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A quota on the maximum bytes per-second that each client group can fetch from a broker before the clients in the group are throttled. Defined on a per-broker basis.")

  public Integer getConsumerByteRate() {
    return consumerByteRate;
  }


  public void setConsumerByteRate(Integer consumerByteRate) {
    this.consumerByteRate = consumerByteRate;
  }


  public V1alpha1KafkaUserSpecQuotas controllerMutationRate(BigDecimal controllerMutationRate) {

    this.controllerMutationRate = controllerMutationRate;
    return this;
  }

  /**
   * A quota on the rate at which mutations are accepted for the create topics request, the create partitions request
   * and the delete topics request. The rate is accumulated by the number of partitions created or deleted.
   * minimum: 0
   *
   * @return controllerMutationRate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A quota on the rate at which mutations are accepted for the create topics request, the create partitions request and the delete topics request. The rate is accumulated by the number of partitions created or deleted.")

  public BigDecimal getControllerMutationRate() {
    return controllerMutationRate;
  }


  public void setControllerMutationRate(BigDecimal controllerMutationRate) {
    this.controllerMutationRate = controllerMutationRate;
  }


  public V1alpha1KafkaUserSpecQuotas producerByteRate(Integer producerByteRate) {

    this.producerByteRate = producerByteRate;
    return this;
  }

  /**
   * A quota on the maximum bytes per-second that each client group can publish to a broker before the clients in the
   * group are throttled. Defined on a per-broker basis.
   * minimum: 0
   *
   * @return producerByteRate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A quota on the maximum bytes per-second that each client group can publish to a broker before the clients in the group are throttled. Defined on a per-broker basis.")

  public Integer getProducerByteRate() {
    return producerByteRate;
  }


  public void setProducerByteRate(Integer producerByteRate) {
    this.producerByteRate = producerByteRate;
  }


  public V1alpha1KafkaUserSpecQuotas requestPercentage(Integer requestPercentage) {

    this.requestPercentage = requestPercentage;
    return this;
  }

  /**
   * A quota on the maximum CPU utilization of each client group as a percentage of network and I/O threads.
   * minimum: 0
   *
   * @return requestPercentage
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A quota on the maximum CPU utilization of each client group as a percentage of network and I/O threads.")

  public Integer getRequestPercentage() {
    return requestPercentage;
  }


  public void setRequestPercentage(Integer requestPercentage) {
    this.requestPercentage = requestPercentage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1KafkaUserSpecQuotas v1alpha1KafkaUserSpecQuotas = (V1alpha1KafkaUserSpecQuotas) o;
    return Objects.equals(this.consumerByteRate, v1alpha1KafkaUserSpecQuotas.consumerByteRate) &&
      Objects.equals(this.controllerMutationRate, v1alpha1KafkaUserSpecQuotas.controllerMutationRate) &&
      Objects.equals(this.producerByteRate, v1alpha1KafkaUserSpecQuotas.producerByteRate) &&
      Objects.equals(this.requestPercentage, v1alpha1KafkaUserSpecQuotas.requestPercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumerByteRate, controllerMutationRate, producerByteRate, requestPercentage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1KafkaUserSpecQuotas {\n");
    sb.append("    consumerByteRate: ").append(toIndentedString(consumerByteRate)).append("\n");
    sb.append("    controllerMutationRate: ").append(toIndentedString(controllerMutationRate)).append("\n");
    sb.append("    producerByteRate: ").append(toIndentedString(producerByteRate)).append("\n");
    sb.append("    requestPercentage: ").append(toIndentedString(requestPercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

