/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dissi.kafkaworkshop.kubernetes.kafka.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * The specification of the user.
 */
@ApiModel(description = "The specification of the user.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-23T10:08:26.048Z[Etc/UTC]")
public class V1alpha1KafkaUserSpec {

  public static final String SERIALIZED_NAME_AUTHENTICATION = "authentication";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION)
  private V1alpha1KafkaUserSpecAuthentication authentication;

  public static final String SERIALIZED_NAME_AUTHORIZATION = "authorization";
  @SerializedName(SERIALIZED_NAME_AUTHORIZATION)
  private V1alpha1KafkaUserSpecAuthorization authorization;

  public static final String SERIALIZED_NAME_QUOTAS = "quotas";
  @SerializedName(SERIALIZED_NAME_QUOTAS)
  private V1alpha1KafkaUserSpecQuotas quotas;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private V1alpha1KafkaUserSpecTemplate template;


  public V1alpha1KafkaUserSpec authentication(V1alpha1KafkaUserSpecAuthentication authentication) {

    this.authentication = authentication;
    return this;
  }

  /**
   * Get authentication
   *
   * @return authentication
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1KafkaUserSpecAuthentication getAuthentication() {
    return authentication;
  }


  public void setAuthentication(V1alpha1KafkaUserSpecAuthentication authentication) {
    this.authentication = authentication;
  }


  public V1alpha1KafkaUserSpec authorization(V1alpha1KafkaUserSpecAuthorization authorization) {

    this.authorization = authorization;
    return this;
  }

  /**
   * Get authorization
   *
   * @return authorization
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1KafkaUserSpecAuthorization getAuthorization() {
    return authorization;
  }


  public void setAuthorization(V1alpha1KafkaUserSpecAuthorization authorization) {
    this.authorization = authorization;
  }


  public V1alpha1KafkaUserSpec quotas(V1alpha1KafkaUserSpecQuotas quotas) {

    this.quotas = quotas;
    return this;
  }

  /**
   * Get quotas
   *
   * @return quotas
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1KafkaUserSpecQuotas getQuotas() {
    return quotas;
  }


  public void setQuotas(V1alpha1KafkaUserSpecQuotas quotas) {
    this.quotas = quotas;
  }


  public V1alpha1KafkaUserSpec template(V1alpha1KafkaUserSpecTemplate template) {

    this.template = template;
    return this;
  }

  /**
   * Get template
   *
   * @return template
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1KafkaUserSpecTemplate getTemplate() {
    return template;
  }


  public void setTemplate(V1alpha1KafkaUserSpecTemplate template) {
    this.template = template;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1KafkaUserSpec v1alpha1KafkaUserSpec = (V1alpha1KafkaUserSpec) o;
    return Objects.equals(this.authentication, v1alpha1KafkaUserSpec.authentication) &&
      Objects.equals(this.authorization, v1alpha1KafkaUserSpec.authorization) &&
      Objects.equals(this.quotas, v1alpha1KafkaUserSpec.quotas) &&
      Objects.equals(this.template, v1alpha1KafkaUserSpec.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authentication, authorization, quotas, template);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1KafkaUserSpec {\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    authorization: ").append(toIndentedString(authorization)).append("\n");
    sb.append("    quotas: ").append(toIndentedString(quotas)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

