/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dissi.kafkaworkshop.kubernetes.kafka.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * The status of the Kafka User.
 */
@ApiModel(description = "The status of the Kafka User.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-23T10:08:26.048Z[Etc/UTC]")
public class V1alpha1KafkaUserStatus {

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha1KafkaUserStatusConditions> conditions = null;

  public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
  @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
  private Integer observedGeneration;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private String secret;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;


  public V1alpha1KafkaUserStatus conditions(List<V1alpha1KafkaUserStatusConditions> conditions) {

    this.conditions = conditions;
    return this;
  }

  public V1alpha1KafkaUserStatus addConditionsItem(V1alpha1KafkaUserStatusConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

  /**
   * List of status conditions.
   *
   * @return conditions
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of status conditions.")

  public List<V1alpha1KafkaUserStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha1KafkaUserStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1alpha1KafkaUserStatus observedGeneration(Integer observedGeneration) {

    this.observedGeneration = observedGeneration;
    return this;
  }

  /**
   * The generation of the CRD that was last reconciled by the operator.
   *
   * @return observedGeneration
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The generation of the CRD that was last reconciled by the operator.")

  public Integer getObservedGeneration() {
    return observedGeneration;
  }


  public void setObservedGeneration(Integer observedGeneration) {
    this.observedGeneration = observedGeneration;
  }


  public V1alpha1KafkaUserStatus secret(String secret) {

    this.secret = secret;
    return this;
  }

  /**
   * The name of &#x60;Secret&#x60; where the credentials are stored.
   *
   * @return secret
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of `Secret` where the credentials are stored.")

  public String getSecret() {
    return secret;
  }


  public void setSecret(String secret) {
    this.secret = secret;
  }


  public V1alpha1KafkaUserStatus username(String username) {

    this.username = username;
    return this;
  }

  /**
   * Username.
   *
   * @return username
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Username.")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1KafkaUserStatus v1alpha1KafkaUserStatus = (V1alpha1KafkaUserStatus) o;
    return Objects.equals(this.conditions, v1alpha1KafkaUserStatus.conditions) &&
      Objects.equals(this.observedGeneration, v1alpha1KafkaUserStatus.observedGeneration) &&
      Objects.equals(this.secret, v1alpha1KafkaUserStatus.secret) &&
      Objects.equals(this.username, v1alpha1KafkaUserStatus.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, observedGeneration, secret, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1KafkaUserStatus {\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

